const ACCOUNT_TARGET = 'account'
const GRID_REFRESH = 'render'
const ADDRESS_MODEL_NAME = 'm_address'
const DB_ACTION_SYNCING = 0
const DB_ACTION_DONE = 1
const INDEXDB_TYPE = 1
const SYNC_DATA = 2

export {
  ACCOUNT_TARGET, GRID_REFRESH, 
  ADDRESS_MODEL_NAME, 
  DB_ACTION_SYNCING, DB_ACTION_DONE,
  INDEXDB_TYPE, SYNC_DATA
}
