default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    username: <%= ENV['PELO_MAIN_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_MAIN_DATABASE_PASSWORD'] %>
    migrations_paths: db/migrate
    database: pelo_development
  configuration:
    <<: *default
    username: <%= ENV['PELO_CONFIGURATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONFIGURATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/configuration_migrate
    database: pelo_configuration
  product:
    <<: *default
    username: <%= ENV['PELO_PRODUCT_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_PRODUCT_DATABASE_PASSWORD'] %>
    migrations_paths: db/product_migrate
    database: pelo_product
  conversation:
    <<: *default
    username: <%= ENV['PELO_CONVERSATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONVERSATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/conversation_migrate
    database: pelo_conversation

test:
  <<: *default
  username: <%= ENV['PELO_MAIN_DATABASE_USERNAME'] %>
  password: <%= ENV['PELO_MAIN_DATABASE_PASSWORD'] %>
  database: pelo_test

production:
  primary:
    <<: *default
    username: <%= ENV['PELO_MAIN_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_MAIN_DATABASE_PASSWORD'] %>
    migrations_paths: db/migrate
    database: pelo_main
  configuration:
    <<: *default
    username: <%= ENV['PELO_CONFIGURATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONFIGURATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/configuration_migrate
    database: pelo_configuration
  product:
    <<: *default
    username: <%= ENV['PELO_PRODUCT_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_PRODUCT_DATABASE_PASSWORD'] %>
    migrations_paths: db/product_migrate
    database: pelo_product
  conversation:
    <<: *default
    username: <%= ENV['PELO_CONVERSATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONVERSATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/conversation_migrate
    database: pelo_conversation