default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    username: <%= ENV['PELO_MAIN_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_MAIN_DATABASE_PASSWORD'] %>
    migrations_paths: db/migrate
    database: vidia_development
  primary_replica:
    <<: *default
    username: <%= ENV['DATABASE_USER_READONLY'] %>
    password: <%= ENV['DATABASE_USER_PASSWORD'] %>
    database: vidia_development
    replica: true
  configuration:
    <<: *default
    username: <%= ENV['PELO_CONFIGURATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONFIGURATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/configuration_migrate
    database: vidia_configuration
  product:
    <<: *default
    username: <%= ENV['PELO_PRODUCT_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_PRODUCT_DATABASE_PASSWORD'] %>
    migrations_paths: db/product_migrate
    database: vidia_product
  conversation:
    <<: *default
    username: <%= ENV['PELO_CONVERSATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONVERSATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/conversation_migrate
    database: vidia_conversation
  general:
    <<: *default
    username: <%= ENV['PELO_GENERAL_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_GENERAL_DATABASE_PASSWORD'] %>
    migrations_paths: db/general_migrate
    database: vidia_general

test:
  <<: *default
  username: <%= ENV['PELO_MAIN_DATABASE_USERNAME'] %>
  password: <%= ENV['PELO_MAIN_DATABASE_PASSWORD'] %>
  database: vidia_test

production:
  primary:
    <<: *default
    username: <%= ENV['PELO_MAIN_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_MAIN_DATABASE_PASSWORD'] %>
    migrations_paths: db/migrate
    database: vidia_main
  configuration:
    <<: *default
    username: <%= ENV['PELO_CONFIGURATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONFIGURATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/configuration_migrate
    database: vidia_configuration
  product:
    <<: *default
    username: <%= ENV['PELO_PRODUCT_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_PRODUCT_DATABASE_PASSWORD'] %>
    migrations_paths: db/product_migrate
    database: vidia_product
  conversation:
    <<: *default
    username: <%= ENV['PELO_CONVERSATION_DATABASE_USERNAME'] %>
    password: <%= ENV['PELO_CONVERSATION_DATABASE_PASSWORD'] %>
    migrations_paths: db/conversation_migrate
    database: vidia_conversation